tasks:
 - name: aws-cli
   init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
 - name: react-js
   command: 
     cd frontend-react-js
     npm i     
vscode:
  extensions:
    - 42Crunch.vscode-openapi
